package com.example.stock_portfolio.entity; // Package declaration for the Stocks entity class

import jakarta.persistence.*; // Importing JPA annotations for ORM mapping
import lombok.AllArgsConstructor; // Importing Lombok annotation for generating constructor with all parameters
import lombok.Getter; // Importing Lombok annotation for generating getters
import lombok.NoArgsConstructor; // Importing Lombok annotation for generating no-argument constructor
import lombok.Setter; // Importing Lombok annotation for generating setters

// Lombok annotations to auto-generate getters, setters, constructors
@Getter
@Setter
@NoArgsConstructor // No-argument constructor generated by Lombok
@AllArgsConstructor // All-argument constructor generated by Lombok
@Entity // Marks this class as a JPA entity
@Table(name = "stock") // Specifies the table name in the database
public class Stocks {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates the value for this field using an incremental strategy
    private Long id; // Unique identifier for each stock record

    @Column(name = "stock_name", nullable = false, unique = true) // Maps the field to a column in the database
    private String stockName; // Name of the stock (e.g., 'Tesla')

    @Column(name = "ticker") // Maps the field to a column in the database
    private String ticker; // The ticker symbol for the stock (e.g., 'TSLA')

    @Column(name = "quantity") // Maps the field to a column in the database
    private Long quantity; // Number of shares owned for this stock

    @Column(name = "buy_price") // Maps the field to a column in the database
    private Double buyPrice; // The price at which the stock was bought

    @Column(name = "current_price") // Maps the field to a column in the database
    private Double currentPrice; // The current market price of the stock
}
