version: '3.8'

services:
  app:
    build: .
    container_name: stock-portfolio-app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://portfoliodb.cvmo8mei4xjk.ap-south-1.rds.amazonaws.com/portfoliodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: NoPaswaard123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TWELVE_DATA_API_KEY: your-example-api-key-here # Replace with your actual API key
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: stock-portfolio-db
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NoPaswaard123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
